import {
  ColumnConfig,
  ColumnDefinition,
  ColumnGeneratedType,
  ColumnIdentityConfig,
} from "@dsqlbase/core/definition";

export interface IdentityConfig<T extends IdentityColumnOptions> {
  type: T["type"] extends "BY DEFAULT" ? "BY DEFAULT" : "ALWAYS";
  sequenceName?: T["sequenceName"];
  options: {
    dataType: "bigint";
    cache: number;
    startValue: number;
    increment: number;
    minValue: number;
    maxValue: number;
    cycle: boolean;
  };
}

export class IdentityColumnDefinition<
  TName extends string,
  TIdentity extends IdentityConfig<IdentityColumnOptions>,
> extends ColumnDefinition<
  TName,
  Omit<ColumnConfig<number, string>, "identity"> & {
    notNull: true;
    hasDefault: true;
    identity: TIdentity;
  }
> {
  protected override _identity: ColumnIdentityConfig;

  constructor(
    name: TName,
    config: Partial<
      Omit<ColumnConfig<number, string>, "identity"> & {
        notNull: true;
        hasDefault: true;
        identity: TIdentity;
      }
    >
  ) {
    super(name, config);
    this._identity = config.identity as TIdentity;
  }

  public sequenceName(name: string): this {
    this._identity.sequenceName = name;
    return this;
  }

  public cycle(cycle = true): this {
    this._identity.options.cycle = cycle;
    return this;
  }

  public cache(cache: number): this {
    this._identity.options.cache = cache;
    return this;
  }

  public startValue(startValue: number): this {
    this._identity.options.startValue = startValue;
    return this;
  }

  public increment(increment: number): this {
    this._identity.options.increment = increment;
    return this;
  }

  public minValue(minValue: number): this {
    this._identity.options.minValue = minValue;
    return this;
  }

  public maxValue(maxValue: number): this {
    this._identity.options.maxValue = maxValue;
    return this;
  }
}

export interface IdentityColumnOptions {
  /**
   * Determines how the identity value is generated:
   * - `ALWAYS`: The identity value is always generated by the database, and cannot be overridden by insert statements.
   * - `BY DEFAULT`: The identity value is generated by the database if no value is provided in the insert statement, but can be overridden by providing a value.
   *
   * @default "ALWAYS"
   */
  type: ColumnGeneratedType;

  /**
   * Name of the identity sequence to use for generating values. If not provided, an unused sequence name will be generated automatically.
   */
  sequenceName?: string;
}

/**
 * Defines an identity column in the database schema, which automatically generates unique numeric values for new rows.
 *
 * @param name Column name in the database
 * @param options Configuration options for the identity column
 * @returns Serializable column definition for an identity column.
 */

export function identity<const TName extends string, const TOptions extends IdentityColumnOptions>(
  name: TName,
  options?: TOptions
) {
  const identity = {
    type: options?.type ?? "ALWAYS",
    options: {
      dataType: "bigint",
      cache: 1,
      startValue: 1,
      increment: 1,
      minValue: 1,
      cycle: false,
    },
  } as IdentityConfig<TOptions>;

  return new IdentityColumnDefinition<TName, IdentityConfig<TOptions>>(name, {
    dataType: "bigint",
    identity,
    codec: {
      encode: (value) => value.toString(),
      decode: (value) => Number(value),
    },
  });
}
