import { describe, expect, it } from "vitest";
import { diffTableOperations } from "./table.js";
import { createPrinter } from "../../ddl/index.js";
import { OperationResult } from "./base.js";

const sqlOf = (result: OperationResult) =>
  result.operations.map((op) => createPrinter()(op.statement).text);
import { SerializedObject } from "../../base.js";
import { AnyColumnDefinition, AnyTableDefinition } from "@dsqlbase/core/definition";

type Column = SerializedObject<AnyColumnDefinition>;
type Table = SerializedObject<AnyTableDefinition>;

const idColumn: Column = {
  kind: "COLUMN",
  name: "id",
  dataType: "uuid",
  notNull: true,
  primaryKey: true,
  unique: false,
  defaultValue: "gen_random_uuid()",
  check: null,
  domain: null,
  generated: null,
  identity: null,
} as Column;

const emailColumn: Column = {
  kind: "COLUMN",
  name: "email",
  dataType: "text",
  notNull: false,
  primaryKey: false,
  unique: false,
  defaultValue: null,
  check: null,
  domain: null,
  generated: null,
  identity: null,
} as Column;

const baseTable: Table = {
  kind: "TABLE",
  name: "users",
  namespace: "public",
  columns: [idColumn, emailColumn],
  indexes: [],
  constraints: [],
} as Table;

describe("diffTableOperations — new table", () => {
  const print = createPrinter();

  it("creates an identity column with its sequence options and name", () => {
    const counter = {
      ...emailColumn,
      name: "counter",
      dataType: "bigint",
      notNull: true,
      identity: {
        type: "BY DEFAULT",
        sequenceName: "users_counter_seq",
        options: { dataType: "bigint", cache: 65536, increment: 1, startValue: 1, cycle: false },
      },
    } as unknown as Column;

    const [create] = diffTableOperations(
      { ...baseTable, columns: [idColumn, counter] },
      undefined
    ).operations;

    expect(create && print(create.statement).text).toContain(
      `"counter" bigint GENERATED BY DEFAULT AS IDENTITY ` +
        `(SEQUENCE NAME "users_counter_seq" AS bigint INCREMENT BY 1 START WITH 1 CACHE 65536 NO CYCLE)`
    );
  });

  it("creates a generated column with its expression", () => {
    const full = {
      ...emailColumn,
      name: "full_name",
      generated: { type: "ALWAYS", expression: `"first" || ' ' || "last"`, mode: "STORED" },
    } as unknown as Column;

    const [create] = diffTableOperations(
      { ...baseTable, columns: [idColumn, full] },
      undefined
    ).operations;

    expect(create && print(create.statement).text).toContain(
      `"full_name" text GENERATED ALWAYS AS ("first" || ' ' || "last") STORED`
    );
  });
});

describe("diffTableOperations — risk and summaries", () => {
  it("rates dropping an index lossy, with the table as its subject", () => {
    const remote: Table = {
      ...baseTable,
      indexes: [
        {
          kind: "INDEX",
          name: "users_email_idx",
          unique: false,
          distinctNulls: true,
          columns: [
            {
              kind: "INDEX_COLUMN",
              name: "users_email_idx_column_email",
              nulls: "LAST",
              column: "email",
            },
          ],
          include: null,
        },
      ],
    } as Table;

    const [drop] = diffTableOperations(baseTable, remote).operations;

    expect(drop?.summary).toMatchObject({
      change: "users.users_email_idx",
      subject: { kind: "TABLE", name: "users" },
      action: "DROP",
      target: { kind: "INDEX", name: "users_email_idx" },
      risk: "lossy",
    });
  });

  it("describes a refused change: subject, action, target and the attributes", () => {
    const generated = { type: "ALWAYS", expression: "upper(name)", mode: "STORED" } as const;
    const local: Table = { ...baseTable, columns: [idColumn, { ...emailColumn, generated }] };

    const [refused] = diffTableOperations(local, baseTable).errors;

    expect(refused?.summary).toEqual({
      subject: { kind: "TABLE", name: "users" },
      action: "ALTER",
      target: { kind: "COLUMN", name: "email" },
      changes: [{ attribute: "generated", from: null, to: generated }],
    });
  });
});

describe("diffTableOperations — existing remote", () => {
  describe("columns", () => {
    it("emits a bare ADD COLUMN for a plain new column", () => {
      const newCol: Column = { ...emailColumn, name: "nickname" };
      const local: Table = { ...baseTable, columns: [...baseTable.columns, newCol] };

      const result = diffTableOperations(local, baseTable);

      expect(result.errors).toEqual([]);
      expect(result.operations).toHaveLength(1);
      expect(result.operations[0]).toMatchObject({
        type: "ALTER",
        statement: {
          __kind: "ALTER_TABLE",
          name: "users",
          actions: [
            {
              __kind: "ADD_COLUMN",
              column: expect.objectContaining({
                name: "nickname",
                notNull: false,
                isPrimaryKey: false,
                unique: false,
                defaultValue: null,
              }),
            },
          ],
        },
      });
    });

    it("ADD COLUMN with unique:true emits bare ADD + index + USING INDEX", () => {
      const newCol: Column = { ...emailColumn, name: "nickname", unique: true };
      const local: Table = { ...baseTable, columns: [...baseTable.columns, newCol] };

      const result = diffTableOperations(local, baseTable);

      expect(result.errors).toEqual([]);
      expect(result.operations).toHaveLength(3);

      const [alter, createIdx, addConstraint] = result.operations;
      expect(alter.statement).toMatchObject({
        __kind: "ALTER_TABLE",
        actions: [{ __kind: "ADD_COLUMN" }],
      });
      expect(createIdx.statement).toMatchObject({
        __kind: "CREATE_INDEX",
        name: "users_nickname_key_idx",
        unique: true,
        async: true,
      });
      expect(addConstraint.statement).toMatchObject({
        __kind: "ALTER_TABLE",
        actions: [
          {
            __kind: "ADD_CONSTRAINT_USING_INDEX",
            name: "users_nickname_key",
            kind: "UNIQUE",
            indexName: "users_nickname_key_idx",
          },
        ],
      });
    });

    it("refuses adding an identity column: it needs a NOT NULL DSQL can't add", () => {
      const counter = {
        ...emailColumn,
        name: "counter",
        dataType: "bigint",
        notNull: true,
        identity: { type: "ALWAYS", options: { cache: 1 } },
      } as unknown as Column;

      const result = diffTableOperations(
        { ...baseTable, columns: [...baseTable.columns, counter] },
        baseTable
      );

      expect(result.operations).toEqual([]);
      expect(result.errors).toEqual([
        expect.objectContaining({ code: "NO_ADD_IDENTITY", subject: "counter" }),
      ]);
    });

    it("ADD COLUMN with a domain data type carries the domain in references", () => {
      const newCol: Column = {
        ...emailColumn,
        name: "address",
        dataType: "email_addr",
        domain: "email_addr",
      };
      const local: Table = { ...baseTable, columns: [...baseTable.columns, newCol] };

      const result = diffTableOperations(local, baseTable);

      expect(result.errors).toEqual([]);
      expect(result.operations).toHaveLength(1);
      expect(result.operations[0]).toMatchObject({
        type: "ALTER",
        statement: {
          actions: [
            {
              __kind: "ADD_COLUMN",
              column: expect.objectContaining({ name: "address", dataType: "email_addr" }),
            },
          ],
        },
      });
      expect(result.operations[0].references).toEqual(expect.arrayContaining(["email_addr"]));
    });

    const withColumn = (column: Partial<Column>) =>
      ({ ...baseTable, columns: [idColumn, { ...emailColumn, ...column }] }) as Table;

    it("adds a column with a default in two steps; existing rows stay NULL", () => {
      const local: Table = {
        ...baseTable,
        columns: [
          ...baseTable.columns,
          { ...emailColumn, name: "status", defaultValue: "'active'" },
        ],
      };

      const result = diffTableOperations(local, baseTable);

      expect(sqlOf(result)).toEqual([
        `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "status" text`,
        `ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'active'`,
      ]);
      expect(result.operations[1]?.summary.note).toMatch(/existing rows stay NULL/);
    });

    it("adds a NOT NULL column with a default: add, default, backfill, NOT NULL as a CHECK", () => {
      const local: Table = {
        ...baseTable,
        columns: [
          ...baseTable.columns,
          { ...emailColumn, name: "status", notNull: true, defaultValue: "'active'" },
        ],
      };

      const result = diffTableOperations(local, baseTable);

      expect(result.errors).toEqual([]);
      expect(sqlOf(result)).toEqual([
        `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "status" text`,
        `ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'active'`,
        `UPDATE "users" SET "status" = DEFAULT WHERE "id" IN (SELECT "id" FROM "users" WHERE "status" IS NULL LIMIT 1000) RETURNING 1`,
        `ALTER TABLE "users" ADD CONSTRAINT "users_status_not_null" CHECK ("status" IS NOT NULL) NOT VALID`,
        `ALTER TABLE ASYNC "users" VALIDATE CONSTRAINT "users_status_not_null"`,
      ]);
      expect(result.operations.map((op) => [op.summary.action, op.summary.risk])).toEqual([
        ["ADD", "safe"],
        ["ADD", "safe"],
        ["BACKFILL", "safe"],
        ["ADD", "safe"],
        ["VALIDATE", "safe"],
      ]);
      expect(new Set(result.operations.map((op) => op.summary.change))).toEqual(
        new Set(["users.status"])
      );
    });

    it("refuses adding a NOT NULL column without a default", () => {
      const local: Table = {
        ...baseTable,
        columns: [...baseTable.columns, { ...emailColumn, name: "status", notNull: true }],
      };

      expect(diffTableOperations(local, baseTable)).toEqual({
        operations: [],
        errors: [expect.objectContaining({ code: "NOT_NULL_NEEDS_DEFAULT", subject: "status" })],
      });
    });

    it("refuses adding a generated column", () => {
      const local: Table = {
        ...baseTable,
        columns: [
          ...baseTable.columns,
          {
            ...emailColumn,
            name: "upper",
            generated: { type: "ALWAYS", expression: "upper(email)", mode: "STORED" },
          },
        ],
      };

      expect(diffTableOperations(local, baseTable).errors).toEqual([
        expect.objectContaining({ code: "NO_ADD_GENERATED_COLUMN" }),
      ]);
    });

    it("drops a removed column (destructive), after the table's other changes", () => {
      const remote: Table = {
        ...baseTable,
        columns: [...baseTable.columns, { ...emailColumn, name: "legacy" }],
        indexes: [
          {
            kind: "INDEX",
            name: "users_legacy_idx",
            unique: false,
            distinctNulls: true,
            columns: [
              {
                kind: "INDEX_COLUMN",
                name: "users_legacy_idx_column_legacy",
                nulls: "LAST",
                column: "legacy",
              },
            ],
            include: null,
            valid: true,
          },
        ],
      } as Table;

      const result = diffTableOperations(baseTable, remote);

      expect(sqlOf(result)).toEqual([
        `DROP INDEX IF EXISTS "users_legacy_idx" RESTRICT`,
        `ALTER TABLE "users" DROP COLUMN IF EXISTS "legacy"`,
      ]);
      expect(result.operations[1]?.summary).toMatchObject({
        risk: "destructive",
        note: "its data is lost",
      });
    });

    it("notes a possible rename when a column is dropped and another added", () => {
      const remote: Table = { ...baseTable, columns: [idColumn, { ...emailColumn, name: "mail" }] };

      const drop = diffTableOperations(baseTable, remote).operations.find(
        (op) => op.summary.action === "DROP"
      );

      expect(drop?.summary.note).toMatch(
        /possible rename: "email" is added.*renamedFrom\("mail"\)/
      );
    });

    it("refuses dropping a primary-key column", () => {
      const local: Table = { ...baseTable, columns: [emailColumn] };

      expect(diffTableOperations(local, baseTable).errors).toEqual(
        expect.arrayContaining([expect.objectContaining({ code: "NO_DROP_PRIMARY_KEY_COLUMN" })])
      );
    });

    it("changes a type by dropping and adding the column again (destructive)", () => {
      const index = {
        kind: "INDEX",
        name: "users_email_idx",
        unique: false,
        distinctNulls: true,
        columns: [
          {
            kind: "INDEX_COLUMN",
            name: "users_email_idx_column_email",
            nulls: "LAST",
            column: "email",
          },
        ],
        include: null,
        valid: true,
      } as Table["indexes"][number];
      const remote: Table = { ...withColumn({}), indexes: [index] };
      const local: Table = {
        ...withColumn({ dataType: "varchar(320)", defaultValue: "''" }),
        indexes: [index],
      };

      const result = diffTableOperations(local, remote);

      expect(result.errors).toEqual([]);
      expect(sqlOf(result)).toEqual([
        `ALTER TABLE "users" DROP COLUMN IF EXISTS "email"`,
        `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "email" varchar(320)`,
        `ALTER TABLE "users" ALTER COLUMN "email" SET DEFAULT ''`,
        `CREATE INDEX ASYNC IF NOT EXISTS "users_email_idx" ON "users" ("email" NULLS LAST) NULLS DISTINCT`,
      ]);
      expect(result.operations[0]?.summary).toMatchObject({
        risk: "destructive",
        changes: [{ attribute: "dataType", from: "text", to: "varchar(320)" }],
        note: expect.stringMatching(/email_v2.*deprecated/),
      });
    });

    it("refuses changing the type of a primary-key column", () => {
      const local: Table = {
        ...baseTable,
        columns: [{ ...idColumn, dataType: "text" }, emailColumn],
      };

      expect(diffTableOperations(local, baseTable).errors).toEqual([
        expect.objectContaining({ code: "NO_ALTER_PRIMARY_KEY_COLUMN" }),
      ]);
    });

    it("sets, changes and drops a default", () => {
      expect(sqlOf(diffTableOperations(withColumn({ defaultValue: "'a'" }), baseTable))).toEqual([
        `ALTER TABLE "users" ALTER COLUMN "email" SET DEFAULT 'a'`,
      ]);
      const dropped = diffTableOperations(baseTable, withColumn({ defaultValue: "'a'" }));
      expect(sqlOf(dropped)).toEqual([`ALTER TABLE "users" ALTER COLUMN "email" DROP DEFAULT`]);
      expect(dropped.operations[0]?.summary.risk).toBe("lossy");
    });

    it("makes a column NOT NULL: backfill with its default, then a CHECK", () => {
      const result = diffTableOperations(
        withColumn({ notNull: true, defaultValue: "''" }),
        withColumn({ defaultValue: "''" })
      );

      expect(sqlOf(result)).toEqual([
        `UPDATE "users" SET "email" = DEFAULT WHERE "id" IN (SELECT "id" FROM "users" WHERE "email" IS NULL LIMIT 1000) RETURNING 1`,
        `ALTER TABLE "users" ADD CONSTRAINT "users_email_not_null" CHECK ("email" IS NOT NULL) NOT VALID`,
        `ALTER TABLE ASYNC "users" VALIDATE CONSTRAINT "users_email_not_null"`,
      ]);
    });

    it("makes a column NOT NULL without a default: validation fails if a NULL is left", () => {
      const result = diffTableOperations(withColumn({ notNull: true }), baseTable);

      expect(sqlOf(result)).toEqual([
        `ALTER TABLE "users" ADD CONSTRAINT "users_email_not_null" CHECK ("email" IS NOT NULL) NOT VALID`,
        `ALTER TABLE ASYNC "users" VALIDATE CONSTRAINT "users_email_not_null"`,
      ]);
      expect(result.operations[1]?.summary.note).toMatch(/fails if a row is NULL/);
    });

    it("reads a NOT NULL CHECK as the column's NOT NULL, and drops it to make the column nullable", () => {
      const viaCheck = withColumn({
        check: {
          kind: "CHECK_CONSTRAINT",
          name: "users_email_not_null",
          expression: "CHECK (email IS NOT NULL)",
          validated: true,
        },
      });

      expect(diffTableOperations(withColumn({ notNull: true }), viaCheck)).toEqual({
        operations: [],
        errors: [],
      });
      expect(sqlOf(diffTableOperations(baseTable, viaCheck))).toEqual([
        `ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_email_not_null" RESTRICT`,
      ]);
    });

    it("validates a NOT NULL CHECK left NOT VALID", () => {
      const pending = withColumn({
        check: {
          kind: "CHECK_CONSTRAINT",
          name: "users_email_not_null",
          expression: "CHECK (email IS NOT NULL)",
          validated: false,
        },
      });

      expect(sqlOf(diffTableOperations(withColumn({ notNull: true }), pending))).toEqual([
        `ALTER TABLE ASYNC "users" VALIDATE CONSTRAINT "users_email_not_null"`,
      ]);
    });

    it("drops a column's NOT NULL (lossy)", () => {
      const result = diffTableOperations(baseTable, withColumn({ notNull: true }));

      expect(sqlOf(result)).toEqual([`ALTER TABLE "users" ALTER COLUMN "email" DROP NOT NULL`]);
      expect(result.operations[0]?.summary.risk).toBe("lossy");
    });

    it("turns a generated column into a plain one (destructive); refuses other generated changes", () => {
      const generated = { type: "ALWAYS", expression: "upper(name)", mode: "STORED" } as const;

      const plain = diffTableOperations(baseTable, withColumn({ generated }));
      expect(sqlOf(plain)).toEqual([`ALTER TABLE "users" ALTER COLUMN "email" DROP EXPRESSION`]);
      expect(plain.operations[0]?.summary.risk).toBe("destructive");

      expect(diffTableOperations(withColumn({ generated }), baseTable).errors).toEqual([
        expect.objectContaining({ code: "NO_ALTER_GENERATED" }),
      ]);
    });

    it("emits UNIQUE promotion path on unique:false → true transition", () => {
      const localUnique: Column = { ...emailColumn, unique: true };
      const local: Table = { ...baseTable, columns: [idColumn, localUnique] };

      const result = diffTableOperations(local, baseTable);

      expect(result.errors).toEqual([]);
      expect(result.operations).toHaveLength(2);

      const [createIdx, addConstraint] = result.operations;
      expect(createIdx.statement).toMatchObject({
        __kind: "CREATE_INDEX",
        name: "users_email_key_idx",
        unique: true,
        async: true,
      });
      expect(addConstraint.statement).toMatchObject({
        __kind: "ALTER_TABLE",
        actions: [
          {
            __kind: "ADD_CONSTRAINT_USING_INDEX",
            name: "users_email_key",
            kind: "UNIQUE",
            indexName: "users_email_key_idx",
          },
        ],
      });
      expect(addConstraint.references).toEqual(
        expect.arrayContaining(["users", "users_email_key_idx"])
      );
    });
  });

  describe("identity", () => {
    const idIdentity = {
      type: "BY DEFAULT" as const,
      sequenceName: "users_id_seq",
      options: {
        dataType: "bigint",
        cache: 1,
        cycle: false,
        increment: 1,
        minValue: 1,
        maxValue: 1_000_000,
        startValue: 1,
        ownedBy: undefined,
      },
    };

    it("emits ALTER COLUMN ADD IDENTITY when added", () => {
      const local: Table = {
        ...baseTable,
        columns: [{ ...idColumn, identity: idIdentity }, emailColumn],
      };

      const result = diffTableOperations(local, baseTable);

      expect(result.errors).toEqual([]);
      expect(result.operations).toHaveLength(1);
      expect(result.operations[0].statement).toMatchObject({
        __kind: "ALTER_TABLE",
        actions: [
          {
            __kind: "ALTER_COLUMN",
            columnName: "id",
            actions: [{ __kind: "ADD_IDENTITY", mode: "BY_DEFAULT" }],
          },
        ],
      });
    });

    it("emits ALTER COLUMN DROP IDENTITY when removed", () => {
      const remote: Table = {
        ...baseTable,
        columns: [{ ...idColumn, identity: idIdentity }, emailColumn],
      };

      const result = diffTableOperations(baseTable, remote);

      expect(result.errors).toEqual([]);
      expect(result.operations).toHaveLength(1);
      expect(result.operations[0].statement).toMatchObject({
        __kind: "ALTER_TABLE",
        actions: [
          {
            __kind: "ALTER_COLUMN",
            actions: [{ __kind: "DROP_IDENTITY", ifExists: true }],
          },
        ],
      });
    });

    it("sets the mode and the options in place; startValue with SET START, never RESTART", () => {
      const localIdentity = {
        ...idIdentity,
        type: "ALWAYS" as const,
        options: { ...idIdentity.options, startValue: 1000, increment: 5 },
      };
      const local: Table = {
        ...baseTable,
        columns: [{ ...idColumn, identity: localIdentity }, emailColumn],
      };
      const remote: Table = {
        ...baseTable,
        columns: [{ ...idColumn, identity: idIdentity }, emailColumn],
      };

      const result = diffTableOperations(local, remote);

      expect(result.errors).toEqual([]);
      expect(sqlOf(result)).toEqual([
        `ALTER TABLE "users" ALTER COLUMN "id" SET GENERATED ALWAYS`,
        `ALTER TABLE "users" ALTER COLUMN "id" SET INCREMENT BY 5 SET START WITH 1000`,
      ]);
      expect(result.operations.map((op) => op.summary.risk)).toEqual(["safe", "safe"]);
    });

    it("refuses making a nullable column an identity", () => {
      const local: Table = {
        ...baseTable,
        columns: [idColumn, { ...emailColumn, dataType: "bigint", identity: idIdentity }],
      };
      const remote: Table = {
        ...baseTable,
        columns: [idColumn, { ...emailColumn, dataType: "bigint" }],
      };

      expect(diffTableOperations(local, remote).errors).toEqual([
        expect.objectContaining({ code: "NO_ADD_IDENTITY" }),
      ]);
    });
  });

  describe("indexes", () => {
    const idx = {
      kind: "INDEX" as const,
      name: "users_email_idx",
      unique: false,
      distinctNulls: true,
      columns: [
        {
          kind: "INDEX_COLUMN" as const,
          name: "users_email_idx_column_email" as const,
          nulls: "LAST" as const,
          column: "email",
        },
      ],
      include: null,
    };

    it("emits CREATE INDEX ASYNC when an index is added", () => {
      const local: Table = { ...baseTable, indexes: [idx] };

      const result = diffTableOperations(local, baseTable);

      expect(result.errors).toEqual([]);
      expect(result.operations).toHaveLength(1);
      expect(result.operations[0].statement).toMatchObject({
        __kind: "CREATE_INDEX",
        name: "users_email_idx",
        async: true,
      });
    });

    it("emits DROP INDEX RESTRICT when an index is removed", () => {
      const remote: Table = { ...baseTable, indexes: [idx] };

      const result = diffTableOperations(baseTable, remote);

      expect(result.errors).toEqual([]);
      expect(result.operations).toHaveLength(1);
      expect(result.operations[0].statement).toMatchObject({
        __kind: "DROP_INDEX",
        name: "users_email_idx",
        cascade: "RESTRICT",
      });
    });

    // The old index serves reads, and enforces uniqueness, until the new one is built.
    it("rebuilds a changed index beside the old one, then swaps it in, as one change", () => {
      const local: Table = { ...baseTable, indexes: [{ ...idx, unique: true }] };
      const remote: Table = { ...baseTable, indexes: [idx] };

      const result = diffTableOperations(local, remote);

      expect(result.errors).toEqual([]);
      expect(sqlOf(result)).toEqual([
        `CREATE UNIQUE INDEX ASYNC IF NOT EXISTS "users_email_idx_rebuild" ON "users" ("email" NULLS LAST) NULLS DISTINCT`,
        `DROP INDEX IF EXISTS "users_email_idx" RESTRICT`,
        `ALTER INDEX "users_email_idx_rebuild" RENAME TO "users_email_idx"`,
      ]);
      expect(
        result.operations.map((op) => [`${op.summary.step}/${op.summary.steps}`, op.summary.risk])
      ).toEqual([
        ["1/3", "safe"],
        ["2/3", "lossy"],
        ["3/3", "safe"],
      ]);
    });

    it("rebuilds an index whose async build failed", () => {
      const remote: Table = { ...baseTable, indexes: [{ ...idx, valid: false }] };
      const local: Table = { ...baseTable, indexes: [{ ...idx, valid: true }] };

      expect(sqlOf(diffTableOperations(local, remote))).toEqual([
        `CREATE INDEX ASYNC IF NOT EXISTS "users_email_idx_rebuild" ON "users" ("email" NULLS LAST) NULLS DISTINCT`,
        `DROP INDEX IF EXISTS "users_email_idx" RESTRICT`,
        `ALTER INDEX "users_email_idx_rebuild" RENAME TO "users_email_idx"`,
      ]);
    });

    // A run that stopped part-way leaves the rebuild's index; the next one starts it over.
    it("drops a rebuild's leftover before building it again", () => {
      const local: Table = { ...baseTable, indexes: [{ ...idx, unique: true }] };
      const remote: Table = {
        ...baseTable,
        indexes: [idx, { ...idx, name: "users_email_idx_rebuild", unique: true, valid: false }],
      };

      const result = diffTableOperations(local, remote);

      expect(sqlOf(result)).toEqual([
        `DROP INDEX IF EXISTS "users_email_idx_rebuild" RESTRICT`,
        `CREATE UNIQUE INDEX ASYNC IF NOT EXISTS "users_email_idx_rebuild" ON "users" ("email" NULLS LAST) NULLS DISTINCT`,
        `DROP INDEX IF EXISTS "users_email_idx" RESTRICT`,
        `ALTER INDEX "users_email_idx_rebuild" RENAME TO "users_email_idx"`,
      ]);
      expect(new Set(result.operations.map((op) => op.summary.change)).size).toBe(1);
    });

    it("builds the index, then drops the leftover, when a rebuild stopped after the drop", () => {
      const local: Table = { ...baseTable, indexes: [{ ...idx, unique: true }] };
      const remote: Table = {
        ...baseTable,
        indexes: [{ ...idx, name: "users_email_idx_rebuild", unique: true }],
      };

      expect(sqlOf(diffTableOperations(local, remote))).toEqual([
        `CREATE UNIQUE INDEX ASYNC IF NOT EXISTS "users_email_idx" ON "users" ("email" NULLS LAST) NULLS DISTINCT`,
        `DROP INDEX IF EXISTS "users_email_idx_rebuild" RESTRICT`,
      ]);
    });
  });

  describe("constraints", () => {
    const uniqueConstraint = {
      kind: "UNIQUE_CONSTRAINT" as const,
      name: "users_email_unique",
      columns: ["email"],
      include: null,
      distinctNulls: true,
    };
    const pkConstraint = {
      kind: "PRIMARY_KEY_CONSTRAINT" as const,
      name: "users_pk",
      columns: ["id"],
      include: null,
    };
    const checkConstraint = {
      kind: "CHECK_CONSTRAINT" as const,
      name: "users_email_chk",
      expression: "email <> ''",
    };

    it("emits CREATE INDEX + USING INDEX when a UNIQUE constraint is added", () => {
      const local: Table = { ...baseTable, constraints: [uniqueConstraint] };

      const result = diffTableOperations(local, baseTable);

      expect(result.errors).toEqual([]);
      expect(result.operations).toHaveLength(2);

      const [createIdx, addConstraint] = result.operations;
      expect(createIdx.statement).toMatchObject({
        __kind: "CREATE_INDEX",
        name: "users_email_unique_idx",
        unique: true,
        async: true,
      });
      expect(addConstraint.statement).toMatchObject({
        __kind: "ALTER_TABLE",
        actions: [
          {
            __kind: "ADD_CONSTRAINT_USING_INDEX",
            name: "users_email_unique",
            kind: "UNIQUE",
            indexName: "users_email_unique_idx",
          },
        ],
      });
    });

    it("adds a CHECK constraint NOT VALID, then validates it", () => {
      const local: Table = { ...baseTable, constraints: [checkConstraint] };

      const result = diffTableOperations(local, baseTable);

      expect(result.errors).toEqual([]);
      expect(sqlOf(result)).toEqual([
        `ALTER TABLE "users" ADD CONSTRAINT "users_email_chk" CHECK (email <> '') NOT VALID`,
        `ALTER TABLE ASYNC "users" VALIDATE CONSTRAINT "users_email_chk"`,
      ]);
      expect(result.operations.map((op) => op.summary)).toEqual([
        expect.objectContaining({ action: "ADD", step: 1, steps: 2, risk: "safe", async: false }),
        expect.objectContaining({
          action: "VALIDATE",
          step: 2,
          steps: 2,
          risk: "safe",
          async: true,
        }),
      ]);
    });

    it("validates without ASYNC when asyncIndexes is off (PGlite, Postgres)", () => {
      const local: Table = { ...baseTable, constraints: [checkConstraint] };

      const result = diffTableOperations(local, baseTable, { asyncIndexes: false, ifExists: true });

      expect(sqlOf(result)[1]).toBe(`ALTER TABLE "users" VALIDATE CONSTRAINT "users_email_chk"`);
    });

    it("validates a CHECK left NOT VALID, and does nothing else", () => {
      const local: Table = { ...baseTable, constraints: [{ ...checkConstraint, validated: true }] };
      const remote: Table = {
        ...baseTable,
        constraints: [{ ...checkConstraint, validated: false }],
      };

      expect(sqlOf(diffTableOperations(local, remote))).toEqual([
        `ALTER TABLE ASYNC "users" VALIDATE CONSTRAINT "users_email_chk"`,
      ]);
    });

    it("drops a removed CHECK constraint (lossy)", () => {
      const remote: Table = { ...baseTable, constraints: [checkConstraint] };

      const result = diffTableOperations(baseTable, remote);

      expect(sqlOf(result)).toEqual([
        `ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_email_chk" RESTRICT`,
      ]);
      expect(result.operations[0]?.summary.risk).toBe("lossy");
    });

    it("drops a removed UNIQUE constraint, and its index with it", () => {
      const remote: Table = { ...baseTable, constraints: [uniqueConstraint] };

      expect(sqlOf(diffTableOperations(baseTable, remote))).toEqual([
        `ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_email_unique" RESTRICT`,
      ]);
    });

    // The old constraint enforces uniqueness while the new index builds.
    it("rebuilds a UNIQUE constraint whose columns changed: index, drop, promote", () => {
      const remote: Table = { ...baseTable, constraints: [uniqueConstraint] };
      const local: Table = {
        ...baseTable,
        constraints: [{ ...uniqueConstraint, columns: ["email", "id"] }],
      };

      const result = diffTableOperations(local, remote);

      expect(result.errors).toEqual([]);
      expect(sqlOf(result)).toEqual([
        `CREATE UNIQUE INDEX ASYNC IF NOT EXISTS "users_email_unique_idx" ON "users" ("email" NULLS LAST, "id" NULLS LAST) NULLS DISTINCT`,
        `ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_email_unique" RESTRICT`,
        `ALTER TABLE "users" ADD CONSTRAINT "users_email_unique" UNIQUE USING INDEX "users_email_unique_idx"`,
      ]);
      expect(result.operations.map((op) => op.summary.risk)).toEqual(["safe", "lossy", "safe"]);
    });

    // The key compares by its columns, wherever it was declared: on `id`, or as a constraint.
    it("matches a column's primaryKey flag with a key constraint on the same columns", () => {
      const local: Table = { ...baseTable, constraints: [pkConstraint] };

      expect(diffTableOperations(local, baseTable)).toEqual({ operations: [], errors: [] });
    });

    it("refuses adding, dropping or changing the primary key", () => {
      const keyless: Table = {
        ...baseTable,
        columns: [{ ...idColumn, primaryKey: false }, emailColumn],
      };
      const widened: Table = {
        ...baseTable,
        constraints: [{ ...pkConstraint, columns: ["id", "email"] }],
      };

      for (const [local, remote, action] of [
        [baseTable, keyless, "ADD"],
        [keyless, baseTable, "DROP"],
        [widened, baseTable, "ALTER"],
      ] as const) {
        const { operations, errors } = diffTableOperations(local, remote);

        expect(operations).toEqual([]);
        expect(errors).toEqual([
          expect.objectContaining({
            code: "IMMUTABLE_CONSTRAINT",
            summary: expect.objectContaining({ action }),
          }),
        ]);
      }
    });
  });

  describe("column constraints", () => {
    const check = {
      kind: "CHECK_CONSTRAINT" as const,
      name: "email_check",
      expression: "email <> ''",
    };

    it("adds a column CHECK NOT VALID, then validates it", () => {
      const local: Table = { ...baseTable, columns: [idColumn, { ...emailColumn, check }] };

      expect(sqlOf(diffTableOperations(local, baseTable))).toEqual([
        `ALTER TABLE "users" ADD CONSTRAINT "email_check" CHECK (email <> '') NOT VALID`,
        `ALTER TABLE ASYNC "users" VALIDATE CONSTRAINT "email_check"`,
      ]);
    });

    it("replaces a renamed column CHECK: drop the old, add and validate the new", () => {
      const remote: Table = { ...baseTable, columns: [idColumn, { ...emailColumn, check }] };
      const local: Table = {
        ...baseTable,
        columns: [idColumn, { ...emailColumn, check: { ...check, name: "email_not_blank" } }],
      };

      expect(sqlOf(diffTableOperations(local, remote))).toEqual([
        `ALTER TABLE "users" ADD CONSTRAINT "email_not_blank" CHECK (email <> '') NOT VALID`,
        `ALTER TABLE ASYNC "users" VALIDATE CONSTRAINT "email_not_blank"`,
        `ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "email_check" RESTRICT`,
      ]);
    });

    it("treats a one-column CHECK declared on the table as the column's, by name", () => {
      const local: Table = { ...baseTable, constraints: [check] };
      const remote: Table = { ...baseTable, columns: [idColumn, { ...emailColumn, check }] };

      expect(diffTableOperations(local, remote)).toEqual({ operations: [], errors: [] });
    });

    it("validates a column CHECK left NOT VALID", () => {
      const remote: Table = {
        ...baseTable,
        columns: [idColumn, { ...emailColumn, check: { ...check, validated: false } }],
      };
      const local: Table = {
        ...baseTable,
        columns: [idColumn, { ...emailColumn, check: { ...check, validated: true } }],
      };

      expect(sqlOf(diffTableOperations(local, remote))).toEqual([
        `ALTER TABLE ASYNC "users" VALIDATE CONSTRAINT "email_check"`,
      ]);
    });

    it("drops a column's UNIQUE constraint by its conventional name", () => {
      const remote: Table = { ...baseTable, columns: [idColumn, { ...emailColumn, unique: true }] };

      const result = diffTableOperations(baseTable, remote);

      expect(sqlOf(result)).toEqual([
        `ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_email_key" RESTRICT`,
      ]);
      expect(result.operations[0]?.summary.risk).toBe("lossy");
    });
  });
});

// A bare name resolves through `search_path`, so a statement on a namespaced table that names it
// unqualified lands in (or drops from) `public` instead.
describe("diffTableOperations — table in a namespace", () => {
  const appTable: Table = { ...baseTable, namespace: "app" };
  const index = {
    kind: "INDEX" as const,
    name: "users_email_idx",
    unique: false,
    distinctNulls: true,
    columns: [
      {
        kind: "INDEX_COLUMN" as const,
        name: "users_email_idx_column_email" as const,
        nulls: "LAST" as const,
        column: "email",
      },
    ],
    include: null,
  };

  /**
   * Each statement's references to the table or its index that are not schema-qualified. The
   * name `CREATE INDEX` gives an index, and the new name `RENAME TO` gives one, are bare by
   * syntax: the index lives in its table's schema.
   */
  const unqualified = (result: OperationResult) =>
    sqlOf(result)
      .map((text) =>
        text
          .replace(/^(CREATE (UNIQUE )?INDEX (ASYNC )?(IF NOT EXISTS )?)"\w+"/, "$1")
          .replace(/ RENAME TO "\w+"$/, "")
      )
      .filter((text) => /(?<!"app"\.)"(users|users_email_idx)"/.test(text));

  it("creates the table and its indexes in the schema", () => {
    const result = diffTableOperations({ ...appTable, indexes: [index] }, undefined, {
      ifExists: true,
    });

    expect(result.errors).toEqual([]);
    expect(sqlOf(result)[0]).toContain(`CREATE TABLE IF NOT EXISTS "app"."users"`);
    expect(sqlOf(result)[1]).toContain(`ON "app"."users"`);
    expect(unqualified(result)).toEqual([]);
  });

  it("qualifies column, constraint and index changes on an existing table", () => {
    const local: Table = {
      ...appTable,
      columns: [
        idColumn,
        { ...emailColumn, notNull: true, defaultValue: "'none'", deprecated: true },
        { ...emailColumn, name: "handle", unique: true },
      ],
      indexes: [{ ...index, unique: true }],
      constraints: [
        { kind: "CHECK_CONSTRAINT", name: "users_email_set", expression: `"email" <> ''` },
      ],
    } as Table;
    const remote: Table = { ...appTable, indexes: [index] };

    const result = diffTableOperations(local, remote, { ifExists: true });

    expect(result.errors).toEqual([]);
    expect(sqlOf(result).length).toBeGreaterThan(5);
    expect(unqualified(result)).toEqual([]);
  });

  it("qualifies renames and drops", () => {
    const local: Table = {
      ...appTable,
      columns: [idColumn, { ...emailColumn, name: "mail", renamedFrom: "email" }],
    } as Table;
    const remote: Table = { ...appTable, indexes: [index] };

    const result = diffTableOperations(local, remote, { ifExists: true });

    expect(result.errors).toEqual([]);
    expect(sqlOf(result)).toContain(`DROP INDEX IF EXISTS "app"."users_email_idx" RESTRICT`);
    expect(unqualified(result)).toEqual([]);
  });
});

// A lossy step loses no row data, but the plan must say what it costs while it runs.
describe("diffTableOperations — notes on lossy index and UNIQUE steps", () => {
  const index = {
    kind: "INDEX" as const,
    name: "users_email_idx",
    unique: false,
    distinctNulls: true,
    columns: [
      {
        kind: "INDEX_COLUMN" as const,
        name: "users_email_idx_column_email" as const,
        nulls: "LAST" as const,
        column: "email",
      },
    ],
    include: null,
  };
  const unique = {
    kind: "UNIQUE_CONSTRAINT" as const,
    name: "users_email_unique",
    columns: ["email"],
    include: null,
    distinctNulls: true,
  };
  const notes = (local: Table, remote: Table) =>
    diffTableOperations(local, remote).operations.map((op) => [
      op.summary.action,
      op.summary.note ?? null,
    ]);

  it("notes that an index the definition lacks may have been made by hand", () => {
    expect(notes(baseTable, { ...baseTable, indexes: [index] })).toEqual([
      ["DROP", "not in the definition: removed from it, or created outside it"],
    ]);
  });

  it("notes that a rebuilt index stays in use until the swap", () => {
    const local: Table = { ...baseTable, indexes: [{ ...index, unique: true }] };

    expect(notes(local, { ...baseTable, indexes: [index] })).toEqual([
      ["CREATE", "rebuild of users_email_idx: built beside it, which stays in use until the swap"],
      ["DROP", "replaced by the index built in the step before"],
      ["RENAME", null],
    ]);
  });

  it("notes that a changed UNIQUE constraint isn't enforced between its drop and promotion", () => {
    const local = { ...baseTable, constraints: [{ ...unique, columns: ["email", "id"] }] } as Table;
    const remote = { ...baseTable, constraints: [unique] } as Table;

    expect(notes(local, remote)[1]).toEqual([
      "DROP",
      "replaced by the constraint the next step adds; uniqueness isn't enforced in between",
    ]);
  });
});
