import { describe, expect, it } from "vitest";
import { diffTableOperations } from "./table.js";
import { createPrinter } from "../../ddl/index.js";
import { OperationResult } from "./base.js";

const sqlOf = (result: OperationResult) =>
  result.operations.map((op) => createPrinter()(op.statement).text);
import { SerializedObject } from "../../base.js";
import { AnyColumnDefinition, AnyTableDefinition } from "@dsqlbase/core/definition";

type Column = SerializedObject<AnyColumnDefinition>;
type Table = SerializedObject<AnyTableDefinition>;

const idColumn: Column = {
  kind: "COLUMN",
  name: "id",
  dataType: "uuid",
  notNull: true,
  primaryKey: true,
  unique: false,
  defaultValue: "gen_random_uuid()",
  check: null,
  domain: null,
  generated: null,
  identity: null,
} as Column;

const emailColumn: Column = {
  kind: "COLUMN",
  name: "email",
  dataType: "text",
  notNull: false,
  primaryKey: false,
  unique: false,
  defaultValue: null,
  check: null,
  domain: null,
  generated: null,
  identity: null,
} as Column;

const baseTable: Table = {
  kind: "TABLE",
  name: "users",
  namespace: "public",
  columns: [idColumn, emailColumn],
  indexes: [],
  constraints: [],
} as Table;

describe("diffTableOperations — new table", () => {
  const print = createPrinter();

  it("creates an identity column with its sequence options and name", () => {
    const counter = {
      ...emailColumn,
      name: "counter",
      dataType: "bigint",
      notNull: true,
      identity: {
        type: "BY DEFAULT",
        sequenceName: "users_counter_seq",
        options: { dataType: "bigint", cache: 65536, increment: 1, startValue: 1, cycle: false },
      },
    } as unknown as Column;

    const [create] = diffTableOperations(
      { ...baseTable, columns: [idColumn, counter] },
      undefined
    ).operations;

    expect(create && print(create.statement).text).toContain(
      `"counter" bigint GENERATED BY DEFAULT AS IDENTITY ` +
        `(SEQUENCE NAME "users_counter_seq" AS bigint INCREMENT BY 1 START WITH 1 CACHE 65536 NO CYCLE)`
    );
  });

  it("creates a generated column with its expression", () => {
    const full = {
      ...emailColumn,
      name: "full_name",
      generated: { type: "ALWAYS", expression: `"first" || ' ' || "last"`, mode: "STORED" },
    } as unknown as Column;

    const [create] = diffTableOperations(
      { ...baseTable, columns: [idColumn, full] },
      undefined
    ).operations;

    expect(create && print(create.statement).text).toContain(
      `"full_name" text GENERATED ALWAYS AS ("first" || ' ' || "last") STORED`
    );
  });
});

describe("diffTableOperations — risk and summaries", () => {
  it("rates dropping an index lossy, with the table as its subject", () => {
    const remote: Table = {
      ...baseTable,
      indexes: [
        {
          kind: "INDEX",
          name: "users_email_idx",
          unique: false,
          distinctNulls: true,
          columns: [
            {
              kind: "INDEX_COLUMN",
              name: "users_email_idx_column_email",
              nulls: "LAST",
              column: "email",
            },
          ],
          include: null,
        },
      ],
    } as Table;

    const [drop] = diffTableOperations(baseTable, remote).operations;

    expect(drop?.summary).toMatchObject({
      change: "users.users_email_idx",
      subject: { kind: "TABLE", name: "users" },
      action: "DROP",
      target: { kind: "INDEX", name: "users_email_idx" },
      risk: "lossy",
    });
  });

  it("describes a refused change: subject, action, target and the attributes", () => {
    const local: Table = {
      ...baseTable,
      columns: [idColumn, { ...emailColumn, dataType: "varchar(255)" }],
    };

    const [refused] = diffTableOperations(local, baseTable).errors;

    expect(refused?.summary).toEqual({
      subject: { kind: "TABLE", name: "users" },
      action: "ALTER",
      target: { kind: "COLUMN", name: "email" },
      changes: [{ attribute: "dataType", from: "text", to: "varchar(255)" }],
    });
  });
});

describe("diffTableOperations — existing remote", () => {
  describe("columns", () => {
    it("emits a bare ADD COLUMN for a plain new column", () => {
      const newCol: Column = { ...emailColumn, name: "nickname" };
      const local: Table = { ...baseTable, columns: [...baseTable.columns, newCol] };

      const result = diffTableOperations(local, baseTable);

      expect(result.errors).toEqual([]);
      expect(result.operations).toHaveLength(1);
      expect(result.operations[0]).toMatchObject({
        type: "ALTER",
        statement: {
          __kind: "ALTER_TABLE",
          name: "users",
          actions: [
            {
              __kind: "ADD_COLUMN",
              column: expect.objectContaining({
                name: "nickname",
                notNull: false,
                isPrimaryKey: false,
                unique: false,
                defaultValue: null,
              }),
            },
          ],
        },
      });
    });

    it("ADD COLUMN with unique:true emits bare ADD + index + USING INDEX", () => {
      const newCol: Column = { ...emailColumn, name: "nickname", unique: true };
      const local: Table = { ...baseTable, columns: [...baseTable.columns, newCol] };

      const result = diffTableOperations(local, baseTable);

      expect(result.errors).toEqual([]);
      expect(result.operations).toHaveLength(3);

      const [alter, createIdx, addConstraint] = result.operations;
      expect(alter.statement).toMatchObject({
        __kind: "ALTER_TABLE",
        actions: [{ __kind: "ADD_COLUMN" }],
      });
      expect(createIdx.statement).toMatchObject({
        __kind: "CREATE_INDEX",
        name: "users_nickname_key_idx",
        unique: true,
        async: true,
      });
      expect(addConstraint.statement).toMatchObject({
        __kind: "ALTER_TABLE",
        actions: [
          {
            __kind: "ADD_CONSTRAINT_USING_INDEX",
            name: "users_nickname_key",
            kind: "UNIQUE",
            indexName: "users_nickname_key_idx",
          },
        ],
      });
    });

    it("ADD COLUMN with identity emits bare ADD, then ADD IDENTITY, as two steps of one change", () => {
      const newCol: Column = {
        ...emailColumn,
        name: "counter",
        dataType: "bigint",
        identity: {
          type: "BY DEFAULT",
          sequenceName: "users_counter_seq",
          options: {
            dataType: "bigint",
            cache: 1,
            cycle: false,
            increment: 1,
            minValue: 1,
            maxValue: 1_000_000,
            startValue: 1,
            ownedBy: undefined,
          },
        },
      };
      const local: Table = { ...baseTable, columns: [...baseTable.columns, newCol] };

      const result = diffTableOperations(local, baseTable);

      expect(result.errors).toEqual([]);
      expect(result.operations).toHaveLength(2);
      expect(result.operations[0]?.statement).toMatchObject({
        __kind: "ALTER_TABLE",
        actions: [{ __kind: "ADD_COLUMN", column: expect.objectContaining({ name: "counter" }) }],
      });
      expect(result.operations[1]?.statement).toMatchObject({
        __kind: "ALTER_TABLE",
        actions: [
          {
            __kind: "ALTER_COLUMN",
            columnName: "counter",
            actions: [{ __kind: "ADD_IDENTITY", mode: "BY_DEFAULT" }],
          },
        ],
      });
      expect(result.operations.map((op) => op.summary)).toEqual([
        expect.objectContaining({ change: "users.counter", step: 1, steps: 2, action: "ADD" }),
        expect.objectContaining({ change: "users.counter", step: 2, steps: 2, action: "ADD" }),
      ]);
    });

    it("ADD COLUMN with a domain data type carries the domain in references", () => {
      const newCol: Column = {
        ...emailColumn,
        name: "address",
        dataType: "email_addr",
        domain: "email_addr",
      };
      const local: Table = { ...baseTable, columns: [...baseTable.columns, newCol] };

      const result = diffTableOperations(local, baseTable);

      expect(result.errors).toEqual([]);
      expect(result.operations).toHaveLength(1);
      expect(result.operations[0]).toMatchObject({
        type: "ALTER",
        statement: {
          actions: [
            {
              __kind: "ADD_COLUMN",
              column: expect.objectContaining({ name: "address", dataType: "email_addr" }),
            },
          ],
        },
      });
      expect(result.operations[0].references).toEqual(expect.arrayContaining(["email_addr"]));
    });

    it("refuses ADD COLUMN with notNull/default/check", () => {
      const newCol: Column = {
        ...emailColumn,
        name: "status",
        notNull: true,
        defaultValue: "'active'",
        check: { kind: "CHECK_CONSTRAINT", name: "status_chk", expression: "status <> ''" },
      };
      const local: Table = { ...baseTable, columns: [...baseTable.columns, newCol] };

      const result = diffTableOperations(local, baseTable);

      expect(result.operations).toEqual([]);
      expect(result.errors).toHaveLength(1);
      expect(result.errors[0]).toMatchObject({
        code: "IMMUTABLE_COLUMN",
        subject: "status",
      });
      expect(result.errors[0].message).toContain("NOT NULL");
      expect(result.errors[0].message).toContain("DEFAULT");
      // Its CHECK isn't planned on a column that won't be added.
    });

    it("refuses dropping a column with NO_DROP_COLUMN", () => {
      const local: Table = { ...baseTable, columns: [idColumn] };

      const result = diffTableOperations(local, baseTable);

      expect(result.operations).toEqual([]);
      expect(result.errors).toHaveLength(1);
      expect(result.errors[0]).toMatchObject({
        code: "NO_DROP_COLUMN",
        subject: "email",
      });
    });

    it.each([
      ["dataType", { dataType: "varchar" }],
      ["notNull", { notNull: true }],
      ["defaultValue", { defaultValue: "'x'" }],
      ["domain", { domain: "email_addr" }],
    ])("refuses column modify on %s", (_attr, override) => {
      const modified: Column = { ...emailColumn, ...(override as Partial<Column>) };
      const local: Table = { ...baseTable, columns: [idColumn, modified] };

      const result = diffTableOperations(local, baseTable);

      expect(result.operations).toEqual([]);
      expect(result.errors).toHaveLength(1);
      expect(result.errors[0]).toMatchObject({
        code: "IMMUTABLE_COLUMN",
        subject: "email",
      });
    });

    it("collapses multiple blocked attrs into one IMMUTABLE_COLUMN refusal", () => {
      const modified: Column = {
        ...emailColumn,
        notNull: true,
        defaultValue: "'x'",
      };
      const local: Table = { ...baseTable, columns: [idColumn, modified] };

      const result = diffTableOperations(local, baseTable);

      expect(result.errors).toHaveLength(1);
      const error = result.errors[0];
      expect(error.code).toBe("IMMUTABLE_COLUMN");
      expect(error.diffs?.map((d) => d.key).sort()).toEqual(["defaultValue", "notNull"]);
    });

    it("emits UNIQUE promotion path on unique:false → true transition", () => {
      const localUnique: Column = { ...emailColumn, unique: true };
      const local: Table = { ...baseTable, columns: [idColumn, localUnique] };

      const result = diffTableOperations(local, baseTable);

      expect(result.errors).toEqual([]);
      expect(result.operations).toHaveLength(2);

      const [createIdx, addConstraint] = result.operations;
      expect(createIdx.statement).toMatchObject({
        __kind: "CREATE_INDEX",
        name: "users_email_key_idx",
        unique: true,
        async: true,
      });
      expect(addConstraint.statement).toMatchObject({
        __kind: "ALTER_TABLE",
        actions: [
          {
            __kind: "ADD_CONSTRAINT_USING_INDEX",
            name: "users_email_key",
            kind: "UNIQUE",
            indexName: "users_email_key_idx",
          },
        ],
      });
      expect(addConstraint.references).toEqual(
        expect.arrayContaining(["users", "users_email_key_idx"])
      );
    });
  });

  describe("identity", () => {
    const idIdentity = {
      type: "BY DEFAULT" as const,
      sequenceName: "users_id_seq",
      options: {
        dataType: "bigint",
        cache: 1,
        cycle: false,
        increment: 1,
        minValue: 1,
        maxValue: 1_000_000,
        startValue: 1,
        ownedBy: undefined,
      },
    };

    it("emits ALTER COLUMN ADD IDENTITY when added", () => {
      const local: Table = {
        ...baseTable,
        columns: [{ ...idColumn, identity: idIdentity }, emailColumn],
      };

      const result = diffTableOperations(local, baseTable);

      expect(result.errors).toEqual([]);
      expect(result.operations).toHaveLength(1);
      expect(result.operations[0].statement).toMatchObject({
        __kind: "ALTER_TABLE",
        actions: [
          {
            __kind: "ALTER_COLUMN",
            columnName: "id",
            actions: [{ __kind: "ADD_IDENTITY", mode: "BY_DEFAULT" }],
          },
        ],
      });
    });

    it("emits ALTER COLUMN DROP IDENTITY when removed", () => {
      const remote: Table = {
        ...baseTable,
        columns: [{ ...idColumn, identity: idIdentity }, emailColumn],
      };

      const result = diffTableOperations(baseTable, remote);

      expect(result.errors).toEqual([]);
      expect(result.operations).toHaveLength(1);
      expect(result.operations[0].statement).toMatchObject({
        __kind: "ALTER_TABLE",
        actions: [
          {
            __kind: "ALTER_COLUMN",
            actions: [{ __kind: "DROP_IDENTITY", ifExists: true }],
          },
        ],
      });
    });

    it("emits SET GENERATED and RESTART as two statements when mode and startValue change", () => {
      const localIdentity = {
        ...idIdentity,
        type: "ALWAYS" as const,
        options: { ...idIdentity.options, startValue: 1000 },
      };
      const local: Table = {
        ...baseTable,
        columns: [{ ...idColumn, identity: localIdentity }, emailColumn],
      };
      const remote: Table = {
        ...baseTable,
        columns: [{ ...idColumn, identity: idIdentity }, emailColumn],
      };

      const result = diffTableOperations(local, remote);

      expect(result.errors).toEqual([]);
      expect(result.operations.map((op) => op.statement)).toMatchObject([
        {
          __kind: "ALTER_TABLE",
          actions: [
            { __kind: "ALTER_COLUMN", actions: [{ __kind: "SET_GENERATED", mode: "ALWAYS" }] },
          ],
        },
        {
          __kind: "ALTER_TABLE",
          actions: [{ __kind: "ALTER_COLUMN", actions: [{ __kind: "RESTART", with: 1000 }] }],
        },
      ]);
      expect(result.operations.map((op) => op.summary.risk)).toEqual(["safe", "lossy"]);
    });
  });

  describe("indexes", () => {
    const idx = {
      kind: "INDEX" as const,
      name: "users_email_idx",
      unique: false,
      distinctNulls: true,
      columns: [
        {
          kind: "INDEX_COLUMN" as const,
          name: "users_email_idx_column_email" as const,
          nulls: "LAST" as const,
          column: "email",
        },
      ],
      include: null,
    };

    it("emits CREATE INDEX ASYNC when an index is added", () => {
      const local: Table = { ...baseTable, indexes: [idx] };

      const result = diffTableOperations(local, baseTable);

      expect(result.errors).toEqual([]);
      expect(result.operations).toHaveLength(1);
      expect(result.operations[0].statement).toMatchObject({
        __kind: "CREATE_INDEX",
        name: "users_email_idx",
        async: true,
      });
    });

    it("emits DROP INDEX RESTRICT when an index is removed", () => {
      const remote: Table = { ...baseTable, indexes: [idx] };

      const result = diffTableOperations(baseTable, remote);

      expect(result.errors).toEqual([]);
      expect(result.operations).toHaveLength(1);
      expect(result.operations[0].statement).toMatchObject({
        __kind: "DROP_INDEX",
        name: "users_email_idx",
        cascade: "RESTRICT",
      });
    });

    it("rebuilds a changed index: drop, then create, as one change", () => {
      const local: Table = { ...baseTable, indexes: [{ ...idx, unique: true }] };
      const remote: Table = { ...baseTable, indexes: [idx] };

      const result = diffTableOperations(local, remote);

      expect(result.errors).toEqual([]);
      expect(sqlOf(result)).toEqual([
        `DROP INDEX IF EXISTS "users_email_idx" RESTRICT`,
        `CREATE UNIQUE INDEX ASYNC IF NOT EXISTS "users_email_idx" ON "users" ("email" NULLS LAST) NULLS DISTINCT`,
      ]);
      expect(
        result.operations.map((op) => [`${op.summary.step}/${op.summary.steps}`, op.summary.risk])
      ).toEqual([
        ["1/2", "lossy"],
        ["2/2", "safe"],
      ]);
    });

    it("rebuilds an index whose async build failed", () => {
      const remote: Table = { ...baseTable, indexes: [{ ...idx, valid: false }] };
      const local: Table = { ...baseTable, indexes: [{ ...idx, valid: true }] };

      expect(sqlOf(diffTableOperations(local, remote))).toEqual([
        `DROP INDEX IF EXISTS "users_email_idx" RESTRICT`,
        `CREATE INDEX ASYNC IF NOT EXISTS "users_email_idx" ON "users" ("email" NULLS LAST) NULLS DISTINCT`,
      ]);
    });
  });

  describe("constraints", () => {
    const uniqueConstraint = {
      kind: "UNIQUE_CONSTRAINT" as const,
      name: "users_email_unique",
      columns: ["email"],
      include: null,
      distinctNulls: true,
    };
    const pkConstraint = {
      kind: "PRIMARY_KEY_CONSTRAINT" as const,
      name: "users_pk",
      columns: ["id"],
      include: null,
    };
    const checkConstraint = {
      kind: "CHECK_CONSTRAINT" as const,
      name: "users_email_chk",
      expression: "email <> ''",
    };

    it("emits CREATE INDEX + USING INDEX when a UNIQUE constraint is added", () => {
      const local: Table = { ...baseTable, constraints: [uniqueConstraint] };

      const result = diffTableOperations(local, baseTable);

      expect(result.errors).toEqual([]);
      expect(result.operations).toHaveLength(2);

      const [createIdx, addConstraint] = result.operations;
      expect(createIdx.statement).toMatchObject({
        __kind: "CREATE_INDEX",
        name: "users_email_unique_idx",
        unique: true,
        async: true,
      });
      expect(addConstraint.statement).toMatchObject({
        __kind: "ALTER_TABLE",
        actions: [
          {
            __kind: "ADD_CONSTRAINT_USING_INDEX",
            name: "users_email_unique",
            kind: "UNIQUE",
            indexName: "users_email_unique_idx",
          },
        ],
      });
    });

    it("adds a CHECK constraint NOT VALID, then validates it", () => {
      const local: Table = { ...baseTable, constraints: [checkConstraint] };

      const result = diffTableOperations(local, baseTable);

      expect(result.errors).toEqual([]);
      expect(sqlOf(result)).toEqual([
        `ALTER TABLE "users" ADD CONSTRAINT "users_email_chk" CHECK (email <> '') NOT VALID`,
        `ALTER TABLE ASYNC "users" VALIDATE CONSTRAINT "users_email_chk"`,
      ]);
      expect(result.operations.map((op) => op.summary)).toEqual([
        expect.objectContaining({ action: "ADD", step: 1, steps: 2, risk: "safe", async: false }),
        expect.objectContaining({
          action: "VALIDATE",
          step: 2,
          steps: 2,
          risk: "safe",
          async: true,
        }),
      ]);
    });

    it("validates without ASYNC when asyncIndexes is off (PGlite, Postgres)", () => {
      const local: Table = { ...baseTable, constraints: [checkConstraint] };

      const result = diffTableOperations(local, baseTable, { asyncIndexes: false, ifExists: true });

      expect(sqlOf(result)[1]).toBe(`ALTER TABLE "users" VALIDATE CONSTRAINT "users_email_chk"`);
    });

    it("validates a CHECK left NOT VALID, and does nothing else", () => {
      const local: Table = { ...baseTable, constraints: [{ ...checkConstraint, validated: true }] };
      const remote: Table = {
        ...baseTable,
        constraints: [{ ...checkConstraint, validated: false }],
      };

      expect(sqlOf(diffTableOperations(local, remote))).toEqual([
        `ALTER TABLE ASYNC "users" VALIDATE CONSTRAINT "users_email_chk"`,
      ]);
    });

    it("drops a removed CHECK constraint (lossy)", () => {
      const remote: Table = { ...baseTable, constraints: [checkConstraint] };

      const result = diffTableOperations(baseTable, remote);

      expect(sqlOf(result)).toEqual([
        `ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_email_chk" RESTRICT`,
      ]);
      expect(result.operations[0]?.summary.risk).toBe("lossy");
    });

    it("drops a removed UNIQUE constraint, and its index with it", () => {
      const remote: Table = { ...baseTable, constraints: [uniqueConstraint] };

      expect(sqlOf(diffTableOperations(baseTable, remote))).toEqual([
        `ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_email_unique" RESTRICT`,
      ]);
    });

    it("rebuilds a UNIQUE constraint whose columns changed: drop, index, promote", () => {
      const remote: Table = { ...baseTable, constraints: [uniqueConstraint] };
      const local: Table = {
        ...baseTable,
        constraints: [{ ...uniqueConstraint, columns: ["email", "id"] }],
      };

      const result = diffTableOperations(local, remote);

      expect(result.errors).toEqual([]);
      expect(sqlOf(result)).toEqual([
        `ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_email_unique" RESTRICT`,
        `CREATE UNIQUE INDEX ASYNC IF NOT EXISTS "users_email_unique_idx" ON "users" ("email" NULLS LAST, "id" NULLS LAST) NULLS DISTINCT`,
        `ALTER TABLE "users" ADD CONSTRAINT "users_email_unique" UNIQUE USING INDEX "users_email_unique_idx"`,
      ]);
      expect(result.operations.map((op) => op.summary.risk)).toEqual(["lossy", "safe", "safe"]);
    });

    // The key compares by its columns, wherever it was declared: on `id`, or as a constraint.
    it("matches a column's primaryKey flag with a key constraint on the same columns", () => {
      const local: Table = { ...baseTable, constraints: [pkConstraint] };

      expect(diffTableOperations(local, baseTable)).toEqual({ operations: [], errors: [] });
    });

    it("refuses adding, dropping or changing the primary key", () => {
      const keyless: Table = {
        ...baseTable,
        columns: [{ ...idColumn, primaryKey: false }, emailColumn],
      };
      const widened: Table = {
        ...baseTable,
        constraints: [{ ...pkConstraint, columns: ["id", "email"] }],
      };

      for (const [local, remote, action] of [
        [baseTable, keyless, "ADD"],
        [keyless, baseTable, "DROP"],
        [widened, baseTable, "ALTER"],
      ] as const) {
        const { operations, errors } = diffTableOperations(local, remote);

        expect(operations).toEqual([]);
        expect(errors).toEqual([
          expect.objectContaining({
            code: "IMMUTABLE_CONSTRAINT",
            summary: expect.objectContaining({ action }),
          }),
        ]);
      }
    });
  });

  describe("column constraints", () => {
    const check = {
      kind: "CHECK_CONSTRAINT" as const,
      name: "email_check",
      expression: "email <> ''",
    };

    it("adds a column CHECK NOT VALID, then validates it", () => {
      const local: Table = { ...baseTable, columns: [idColumn, { ...emailColumn, check }] };

      expect(sqlOf(diffTableOperations(local, baseTable))).toEqual([
        `ALTER TABLE "users" ADD CONSTRAINT "email_check" CHECK (email <> '') NOT VALID`,
        `ALTER TABLE ASYNC "users" VALIDATE CONSTRAINT "email_check"`,
      ]);
    });

    it("replaces a renamed column CHECK: drop the old, add and validate the new", () => {
      const remote: Table = { ...baseTable, columns: [idColumn, { ...emailColumn, check }] };
      const local: Table = {
        ...baseTable,
        columns: [idColumn, { ...emailColumn, check: { ...check, name: "email_not_blank" } }],
      };

      expect(sqlOf(diffTableOperations(local, remote))).toEqual([
        `ALTER TABLE "users" ADD CONSTRAINT "email_not_blank" CHECK (email <> '') NOT VALID`,
        `ALTER TABLE ASYNC "users" VALIDATE CONSTRAINT "email_not_blank"`,
        `ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "email_check" RESTRICT`,
      ]);
    });

    it("treats a one-column CHECK declared on the table as the column's, by name", () => {
      const local: Table = { ...baseTable, constraints: [check] };
      const remote: Table = { ...baseTable, columns: [idColumn, { ...emailColumn, check }] };

      expect(diffTableOperations(local, remote)).toEqual({ operations: [], errors: [] });
    });

    it("validates a column CHECK left NOT VALID", () => {
      const remote: Table = {
        ...baseTable,
        columns: [idColumn, { ...emailColumn, check: { ...check, validated: false } }],
      };
      const local: Table = {
        ...baseTable,
        columns: [idColumn, { ...emailColumn, check: { ...check, validated: true } }],
      };

      expect(sqlOf(diffTableOperations(local, remote))).toEqual([
        `ALTER TABLE ASYNC "users" VALIDATE CONSTRAINT "email_check"`,
      ]);
    });

    it("drops a column's UNIQUE constraint by its conventional name", () => {
      const remote: Table = { ...baseTable, columns: [idColumn, { ...emailColumn, unique: true }] };

      const result = diffTableOperations(baseTable, remote);

      expect(sqlOf(result)).toEqual([
        `ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_email_key" RESTRICT`,
      ]);
      expect(result.operations[0]?.summary.risk).toBe("lossy");
    });
  });
});
